---
title: "RStudio e Controle Remoto de Versões pelo Git"
author: "José Maurício Schneedor FS"
---


## Criando um projeto no RStudio para versionamento de código (controle remoto de versões) pelo Git

1. Crie o projeto em *File -> New Project*;
1. Escolha New *Directory*;
1. Escolha *Quarto project*;
1. Digite o nome do diretória a criar;
1. Selecione a caixa *Create a git repository*;
1. Escolha se deseja um editor de texto simples ao iniciar ou um editor visual (*use visual markdown editor*).

## Configurando GitHub

### Instalando e configurando o Git no PC:

|       Num Terminal, digite:
1. sudo apt-get update
1. sudo apt-get install git
1. git version    ; conferindo a instalação
1. git config --global user.name "login de usuário"    ; ex:jaime
1. git config --global user.email "email do usuário"    ; ex: jaime@gmail.com
1. git config user.name ;  conferindo username
1. git config user.email ;  conferindo email

|       Alternativamente, conferindo ambos:

1. git config --global --list

## Criando um repositório no Github

1. Entra no Github;
1. Vá em *Your Repositories* (menu que abre no canto superior direito);
1. Clicar em *New*

<!-- 1. install.packages("usethis") -->
<!-- 1. usethis::use_git_config(user.name = "zemasfs", -->
<!--                         user.email = "zemasfs@gmail.com") -->
<!-- 1. usethis::use_git() -->

<!-- 1. usethis::use_github() -->

### Definindo um *Token* para acesso ao repositório

1. No Github, vá em:
 + Settings
 + Developer Settings
 + Personal access tokens
1. Escolha uma das opções (ex: "Tokens classic")
1. *Generate new token*
 + Escreva uma nota sobre o token;
 + Coloque um período de expiração;
 + Selecione *repo* para os repositórios
1. Clique em *Generate token*

1. Copie essa senha para a próxima etapa, a de *linkar* o projeto local no *RStudio* para acesso remoto no Github.

### *Linkando* o repositório criado ao RStudio

1. Cria o projeto no RStudio, e com *Version Control*
1. Vá à pasta criada e digite os comandos que a página do Github oferece, na sequência:
  + echo "# nome.do.repositório" >> README.md
  +  git init
  + git add README.md
  + git commit -m "first commit"
  + git branch -M main
  + git remote add origin https://github.com/nomeDaContaGit/NomeRepositorioGit.git    ; esse é o *link* oferecido pelo próprio Git
  + git remote add origin 
  + digite a senha (*token*) obtida anteriormente no *site* do Github
  
  *Obs:* 
  - Um *commit* nada mais é do que a imagem das alterações locais realizadas em um projeto, ou seja, um registro de suas alterações. A cada *commit* são geradas remotamente no Github uma versão diferente do projeto, e que pode ser recuperada em caso de falhas, por exemplo.
   - Pode-se colar num Terminal as linhas globalmente, executando-as uma única vez:
   
```{}
echo "# nomeDoRepositorio" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/nomeDoUsuario/nomeDoRepositorio.git
git push -u origin main
```


## Sincronizando o projeto do RStudio com o repositório no Github

1. Reinicie o *RStudio* para aparecer a aba *Git* (se já não apareceu antes);
1. Faça alguma modificação no arquivo do projeto (*md*, *rmd*, *qmd*).
1. Salve o arquivo e/ou renderize (deverá aparecer arquivo na aba *Git* que foi editado localmente);
1. Selecione os arquivos da aba *Git* para sincronização remota (um bom e velho clique  +  Ctrl-A seleciona todos);
1. Clique em *Commit*, e digite qualquer observação no campo; 
1. Clique em *Commit* da nova janela;
1. Clique em *Push*, para envio à nuvem;
1. Digite o *username* para acesso ao Github;
1. Digite o *token* obtido na seção anterior (senha) 
1. Feche as janelas. 

## Clonando um repositório do Git como projeto no RStudio

1. Crie o repositório no *Git*;
1. Crie o projeto em *File -> New Project*;
1. Escolha *Version Control*;
1. Selecione *Git*;
1. Cole o caminho do *link* para o repositório (*Repository URL*);
1. Crie um diretório para o projeto (*Create Project*);
1. Clique em *Create Project*.

## Deletando um repositório
1. Entra no repositório no Git;
1. Vá em *Settings* do repositório (menu superior), e não geral, que fica no canto superior direito;
1. Lá embaixo tem a opção de *delete*.

